pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Setup Environment') {
            steps {
                script {
                    writeFile file: '.env', text: '''
                        REACT_APP_API_URL=http://localhost/api
                        MONGODB_URI=mongodb+srv://sergiogonzzp:2003@inventoryapp.yuxtk.mongodb.net/
                        JWT_SECRET=your_jwt_secret_here
                        PORT=5000
                    '''
                }
            }
        }

        stage('Install Dependencies') {
            parallel {
                stage('Frontend Dependencies') {
                    steps {
                        dir('frontend') {
                            sh 'npm install'
                        }
                    }
                }
                stage('Backend Dependencies') {
                    steps {
                        dir('backend') {
                            sh 'npm install'
                        }
                    }
                }
            }
        }

        stage('Build and Deploy') {
            steps {
                script {
                    // Detener y eliminar contenedores existentes si existen
                    sh '''
                        docker stop inventory-frontend inventory-backend || true
                        docker rm inventory-frontend inventory-backend || true
                    '''
                    
                    // Construir y desplegar
                    sh 'docker compose build'
                    sh 'docker compose up -d'
                }
            }
        }
    }

    post {
        always {
            script {
                sh 'docker compose down || true'
                cleanWs()
            }
        }
        success {
            echo 'Pipeline ejecutado exitosamente!'
        }
        failure {
            echo 'El pipeline ha fallado'
        }
    }
}
