name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    
    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm install
    
    - name: Install Backend Dependencies
      working-directory: ./backend
      run: npm install
    
    - name: Create env file
      run: |
        touch .env
        echo "REACT_APP_API_URL=http://localhost/api" >> .env
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        echo "PORT=5000" >> .env
    
    - name: Run Backend Tests
      working-directory: ./backend
      run: |
        npm run test
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
    
    - name: Build and Deploy with Docker
      run: |
        docker compose build
        docker compose up -d

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        host: ${{ secrets.EC2_HOST }}
        script: |
          cd ~/inventoryapp
          git pull origin main
          docker compose down
          docker compose build
          docker compose up -d
